/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.bambuser.broadcaster.lib;

public final class R {
    public static final class attr {
        public static final int cropToParent = 0x7f020065;
        public static final int denominator = 0x7f020068;
        public static final int numerator = 0x7f0200e0;
    }
    public static final class styleable {
        public static final int[] SurfaceViewWithAutoAR = { 0x7f020065, 0x7f020068, 0x7f0200e0 };
        public static final int SurfaceViewWithAutoAR_cropToParent = 0;
        public static final int SurfaceViewWithAutoAR_denominator = 1;
        public static final int SurfaceViewWithAutoAR_numerator = 2;
    }
}
